### ISSUE TITLE
GitBoard.io integration stopped working

### ISSUE THREAD

**Issue by safris** [gitboard-io/gitboard-action#10]
I'm not exactly sure when this happened, but a couple weeks ago I noticed that my dashboard was empty. I use the Free Plan, and was using GitBoard.io for public repositories. I attempted to follow the instructions for integration of GitHub repositories, but have had no luck. I've successfully authorized all repositories, but when I run builds in these repositories, they do not show up in GitBoards.io. The instructions in the [README.md](https://github.com/gitboard-io/gitboard-action/blob/main/README.md) state that I must get an account key from https://gitboard.io/profile, but when I go to that link I get a 404. I remember doing this a while back, and had put the key as GitHub Secrets to be provided to the `gitboard-io/gitboard-action@main` spec. I found GitBoard.io very useful and convenient, and hope I can get it set up again. Any help would be appreciated!

**Comment by chrisbarbour** [comment]
Thanks for your interest @safris, we have updated how we integrate with GitHub and have stopped using this action to post events to us. We instead use a GitHub App and get webhook events sent to us when you run builds. I will contact you by email to see if we can resolve your issue

**Comment by safris** [comment]
Thank you for your fast response and quick fix @chrisbarbour. GitBoard.io now works for my repositories!
