### ISSUE TITLE
Secrets leakage

### ISSUE THREAD

**Issue by lmilbaum** [gitboard-io/gitboard-action#3]
On boarding the service might expose my secrets. Is that a correct assumption?

**Comment by chrisbarbour** [comment]
Hi @lmilbaum, no secrets will be exposed, we do not forward anything other than the commit message and build numbers / times and we are not granted access to any secret information. Custom actions do not get access to the github action secrets context.

**Comment by lmilbaum** [comment]
> Hi @lmilbaum, no secrets will be exposed, we do not forward anything other than the commit message and build numbers / times and we are not granted access to any secret information. Custom actions do not get access to the github action secrets context.

Thank you for your feedback. I was concerned my org secrets will be leaked to third party service like gitboard.

**Comment by GDownes** [comment]
Hi @lmilbaum,,

We share your concern,
Custom actions only have access to a subset of the GitHub Context objects, the secret context is not accessible to a  custom action.

For context, the Context object provided to Custom actions from the GitHub actions repository:
https://github.com/actions/toolkit/blob/main/packages/github/src/context.ts

From this reduced GitHub Context object we forward a subset of this information using the GitBoard custom action to the GitBoard api:
https://github.com/gitboard-io/gitboard-action/blob/main/pre.ts
