### ISSUE TITLE
GitBoard.io error message: Cannot read properties of undefined (reading 'message')

### ISSUE THREAD

**Issue by lmilbaum** [gitboard-io/gitboard-action#4]
The job result doesn't show on the dashboard. And an error message is thrown.

https://github.com/platform-engineering-org/helper/actions/runs/5197399609/jobs/9372190238?pr=57

**Comment by GDownes** [comment]
Hi @lmilbaum ,
Thanks again for this, we've recreated the issue, hoping to resolve today

**Comment by richard-gibson** [comment]
This is now resolved, we now cover PR build triggers. Updates have been released on v1.1.1

**Comment by GDownes** [comment]
Reopened would be better to ensure the issue is resolved for reporter.

**Comment by lmilbaum** [comment]
> Reopened would be better to ensure the issue is resolved for reporter.

Thanks @GDownes. Issue is resolved.
