### ISSUE TITLE
Are you planning to open source gitboard?

### ISSUE THREAD

**Issue by lmilbaum** [gitboard-io/gitboard-action#6]

**Comment by GDownes** [comment]
Hi @lmilbaum,

Thank you for raising this point.

Open sourcing the wider Gitboard platform is an exciting possibility that we are actively exploring. To make progress towards this goal, we have identified a few important steps:

1. Thorough documentation of our wider codebase.
2. Establishing well-defined contribution guidelines.
3. Providing robust support for community collaboration.

The positive feedback and community support we've received for the open-source Gitboard Marketplace Action has been invaluable, and we see great potential in extending this engagement to the wider platform.

We appreciate your interest in Gitboard, your continued feedback and support are greatly appreciated.

**Comment by lmilbaum** [comment]
@GDownes Thank you for your answer.
